name: bundleSize
on: [pull_request]
defaults:
  run:
    working-directory: frontend
jobs:
  check-bundle-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - /â‰¥uses: sarthak-saxena/JSBundleSize@master
        with:
          bootstrap: yarn
          build_command: yarn build
          dist_path: build
          working-directory: frontend
